/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cnlaunch_mycar_jni_JniX431File */

#ifndef _Included_com_cnlaunch_mycar_jni_JniX431File
#define _Included_com_cnlaunch_mycar_jni_JniX431File
#ifdef __cplusplus
extern "C" {
#endif
#undef com_cnlaunch_mycar_jni_JniX431File_MODE_READ
#define com_cnlaunch_mycar_jni_JniX431File_MODE_READ 1L
#undef com_cnlaunch_mycar_jni_JniX431File_MODE_WRITE
#define com_cnlaunch_mycar_jni_JniX431File_MODE_WRITE 2L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_UNKNOWN
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_UNKNOWN 0L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431 1L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431INFINITE
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431INFINITE 2L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431TOP
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431TOP 3L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431TOOL
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431TOOL 4L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431PC
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_X431PC 5L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_PCLINK
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_PCLINK 17L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_PCCENTER
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_PCCENTER 18L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_ADM
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_ADM 19L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_RECORDER
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_RECORDER 20L
#undef com_cnlaunch_mycar_jni_JniX431File_PRODUCT_CRECORDER
#define com_cnlaunch_mycar_jni_JniX431File_PRODUCT_CRECORDER 21L
#undef com_cnlaunch_mycar_jni_JniX431File_RECORD_DTC
#define com_cnlaunch_mycar_jni_JniX431File_RECORD_DTC 1L
#undef com_cnlaunch_mycar_jni_JniX431File_RECORD_DATASTREAM
#define com_cnlaunch_mycar_jni_JniX431File_RECORD_DATASTREAM 2L
#undef com_cnlaunch_mycar_jni_JniX431File_RECORD_VERSIONINFO
#define com_cnlaunch_mycar_jni_JniX431File_RECORD_VERSIONINFO 4L
#undef com_cnlaunch_mycar_jni_JniX431File_RECORD_FREEZEFRAME
#define com_cnlaunch_mycar_jni_JniX431File_RECORD_FREEZEFRAME 8L
#undef com_cnlaunch_mycar_jni_JniX431File_RECORD_READINESS
#define com_cnlaunch_mycar_jni_JniX431File_RECORD_READINESS 16L
#undef com_cnlaunch_mycar_jni_JniX431File_RECORD_DSBASICS
#define com_cnlaunch_mycar_jni_JniX431File_RECORD_DSBASICS 32L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_OK
#define com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_OK 0L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_LOW_FILEVERSION
#define com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_LOW_FILEVERSION -1L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_HIGH_FILEVERSION
#define com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_HIGH_FILEVERSION -2L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_FILE_NOTFOUND
#define com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_FILE_NOTFOUND -3L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_INCORRECT_FORMAT
#define com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_INCORRECT_FORMAT -4L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_INVALID_PARAMETER
#define com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_INVALID_PARAMETER -5L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_ALLOC_MEMORY
#define com_cnlaunch_mycar_jni_JniX431File_LSX_ERR_ALLOC_MEMORY -6L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_FILE_READABLE
#define com_cnlaunch_mycar_jni_JniX431File_LSX_FILE_READABLE 1L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_FILE_WRITABLE
#define com_cnlaunch_mycar_jni_JniX431File_LSX_FILE_WRITABLE 2L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_FILE_V2
#define com_cnlaunch_mycar_jni_JniX431File_LSX_FILE_V2 4096L
#undef com_cnlaunch_mycar_jni_JniX431File_LSX_FILE_V3
#define com_cnlaunch_mycar_jni_JniX431File_LSX_FILE_V3 8192L
#undef com_cnlaunch_mycar_jni_JniX431File_MAX_DS_COLNUMBER
#define com_cnlaunch_mycar_jni_JniX431File_MAX_DS_COLNUMBER 300L
#undef com_cnlaunch_mycar_jni_JniX431File_DS_TYPE_UNKNOWN
#define com_cnlaunch_mycar_jni_JniX431File_DS_TYPE_UNKNOWN 0L
/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_deinit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1deinit
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_open
 * Signature: (ILcom/cnlaunch/mycar/jni/X431String;ILcom/cnlaunch/mycar/jni/X431Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1open
  (JNIEnv *, jobject, jint, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_checkfile
 * Signature: (Lcom/cnlaunch/mycar/jni/X431String;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1checkfile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_read_baseinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_BASEINFO;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1read_1baseinfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_write_baseinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_BASEINFO;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1write_1baseinfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_read_autoinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_AUTOINFO;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1read_1autoinfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_write_autoinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_AUTOINFO;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1write_1autoinfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_read_spinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_SPINFO;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1read_1spinfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_write_spinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_SPINFO;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1write_1spinfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_read_userinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_USERINFO;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1read_1userinfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_write_userinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_USERINFO;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1write_1userinfo
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_writenewgroup
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1writenewgroup
  (JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_finishnewgroup
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1finishnewgroup
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readgroupcount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readgroupcount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readgroupid
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readgroupid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readgroupinfo
 * Signature: (ILcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readgroupinfo
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readalltype
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readalltype
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_read_fileversion
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1read_1fileversion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_read_langcode
 * Signature: (ILcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1read_1langcode
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_selectreadtextlang
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1selectreadtextlang
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readdtccount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readdtccount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readdtc
 * Signature: (ILcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readdtc
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readdtcinfo
 * Signature: (ILjava/lang/String;Lcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;Lcom/cnlaunch/mycar/jni/X431String;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readdtcinfo
  (JNIEnv *, jobject, jint, jstring, jobject, jobject, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readfirstdtcitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readfirstdtcitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readlastdtcitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readlastdtcitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readnextdtcitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readnextdtcitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readprevdtcitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readprevdtcitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_writedtc
 * Signature: (ILjava/lang/String;Lcom/cnlaunch/mycar/jni/LSX_STRING;Lcom/cnlaunch/mycar/jni/LSX_STRING;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1writedtc
  (JNIEnv *, jobject, jint, jstring, jobject, jobject, jstring);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readdsitemcount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readdsitemcount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readdscolcount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readdscolcount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readdsname
 * Signature: (I[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readdsname
  (JNIEnv *, jobject, jint, jobjectArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readdsunit
 * Signature: (I[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readdsunit
  (JNIEnv *, jobject, jint, jobjectArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readds
 * Signature: (I[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readds
  (JNIEnv *, jobject, jint, jobjectArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readdstype
 * Signature: (I[SI)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readdstype
  (JNIEnv *, jobject, jint, jshortArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readfirstdsitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readfirstdsitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readlastdsitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readlastdsitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readrelndsitem
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readrelndsitem
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_writedsbasics
 * Signature: (I[Lcom/cnlaunch/mycar/jni/LSX_STRING;[Lcom/cnlaunch/mycar/jni/LSX_STRING;[II)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1writedsbasics
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray, jintArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_writeds
 * Signature: (I[Lcom/cnlaunch/mycar/jni/LSX_STRING;I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1writeds
  (JNIEnv *, jobject, jint, jobjectArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_writereadiness
 * Signature: (I[Lcom/cnlaunch/mycar/jni/LSX_STRING;[Lcom/cnlaunch/mycar/jni/LSX_STRING;I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1writereadiness
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_writevi
 * Signature: (ILcom/cnlaunch/mycar/jni/LSX_STRING;)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1writevi
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readffitemcount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readffitemcount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readffcolcount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readffcolcount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readfreezeframe
 * Signature: (ILcom/cnlaunch/mycar/jni/X431String;[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readfreezeframe
  (JNIEnv *, jobject, jint, jobject, jobjectArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readfirstffitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readfirstffitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readlastffitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readlastffitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readnextffitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readnextffitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readprevffitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readprevffitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_writefreezeframe
 * Signature: (ILjava/lang/String;[Lcom/cnlaunch/mycar/jni/LSX_STRING;[Lcom/cnlaunch/mycar/jni/LSX_STRING;[I[Lcom/cnlaunch/mycar/jni/LSX_STRING;I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1writefreezeframe
  (JNIEnv *, jobject, jint, jstring, jobjectArray, jobjectArray, jintArray, jobjectArray, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readitemtype
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readitemtype
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readfirstitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readfirstitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readlastitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readlastitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readnextitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readnextitem
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cnlaunch_mycar_jni_JniX431File
 * Method:    lsx_rec_readprevitem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cnlaunch_mycar_jni_JniX431File_lsx_1rec_1readprevitem
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
