package com.cnlaunch.mycar.im.action;

import com.cnlaunch.mycar.R;

public class FaceManager {
	public static int getUserFace(String faceId) {
		try {
			int id = Integer.parseInt(faceId);
			return getUserFace(id);
		} catch (NumberFormatException e) {
			return R.drawable.userface_1;
		}
	}
	
	public static int getUserFaceGray(String faceId) {
		try {
			int id = Integer.parseInt(faceId);
			return getUserFaceGray(id);
		} catch (NumberFormatException e) {
			return R.drawable.userface_1;
		}
	}

	public static int getChatFace(String faceId) {
		try {
			int id = Integer.parseInt(faceId);
			return getChatFace(id);
		} catch (NumberFormatException e) {
			return 0;
		}
	}

	public static int getChatFace(int id) {
		switch (id) {
		case 0:
			return R.drawable.face_0;
		case 1:
			return R.drawable.face_1;
		case 2:
			return R.drawable.face_2;
		case 3:
			return R.drawable.face_3;
		case 4:
			return R.drawable.face_4;
		case 5:
			return R.drawable.face_5;
		case 6:
			return R.drawable.face_6;
		case 7:
			return R.drawable.face_7;
		case 8:
			return R.drawable.face_8;
		case 9:
			return R.drawable.face_9;
		case 10:
			return R.drawable.face_10;
		case 11:
			return R.drawable.face_11;
		case 12:
			return R.drawable.face_12;
		case 13:
			return R.drawable.face_13;
		case 14:
			return R.drawable.face_14;
		case 15:
			return R.drawable.face_15;
		case 16:
			return R.drawable.face_16;
		case 17:
			return R.drawable.face_17;
		case 18:
			return R.drawable.face_18;
		case 19:
			return R.drawable.face_19;
		case 20:
			return R.drawable.face_20;
		case 21:
			return R.drawable.face_21;
		case 22:
			return R.drawable.face_22;
		case 23:
			return R.drawable.face_23;
		case 24:
			return R.drawable.face_24;
		case 25:
			return R.drawable.face_25;
		case 26:
			return R.drawable.face_26;
		case 27:
			return R.drawable.face_27;
		case 28:
			return R.drawable.face_28;
		case 29:
			return R.drawable.face_29;
		case 30:
			return R.drawable.face_30;
		case 31:
			return R.drawable.face_31;
		case 32:
			return R.drawable.face_32;
		case 33:
			return R.drawable.face_33;
		case 34:
			return R.drawable.face_34;
		case 35:
			return R.drawable.face_35;
		case 36:
			return R.drawable.face_36;
		case 37:
			return R.drawable.face_37;
		case 38:
			return R.drawable.face_38;
		case 39:
			return R.drawable.face_39;
		case 40:
			return R.drawable.face_40;
		case 41:
			return R.drawable.face_41;
		case 42:
			return R.drawable.face_42;
		case 43:
			return R.drawable.face_43;
		case 44:
			return R.drawable.face_44;
		case 45:
			return R.drawable.face_45;
		case 46:
			return R.drawable.face_46;
		case 47:
			return R.drawable.face_47;
		case 48:
			return R.drawable.face_48;
		case 49:
			return R.drawable.face_49;
		case 50:
			return R.drawable.face_50;
		case 51:
			return R.drawable.face_51;
		case 52:
			return R.drawable.face_52;
		case 53:
			return R.drawable.face_53;
		case 54:
			return R.drawable.face_54;
		case 55:
			return R.drawable.face_55;
		case 56:
			return R.drawable.face_56;
		case 57:
			return R.drawable.face_57;
		case 58:
			return R.drawable.face_58;
		case 59:
			return R.drawable.face_59;
		case 60:
			return R.drawable.face_60;
		case 61:
			return R.drawable.face_61;
		case 62:
			return R.drawable.face_62;
		case 63:
			return R.drawable.face_63;
		case 64:
			return R.drawable.face_64;
		case 65:
			return R.drawable.face_65;
		case 66:
			return R.drawable.face_66;
		case 67:
			return R.drawable.face_67;
		case 68:
			return R.drawable.face_68;
		case 69:
			return R.drawable.face_69;
		case 70:
			return R.drawable.face_70;
		case 71:
			return R.drawable.face_71;
		case 72:
			return R.drawable.face_72;
		case 73:
			return R.drawable.face_73;
		case 74:
			return R.drawable.face_74;
		case 75:
			return R.drawable.face_75;
		case 76:
			return R.drawable.face_76;
		case 77:
			return R.drawable.face_77;
		case 78:
			return R.drawable.face_78;
		case 79:
			return R.drawable.face_79;
		case 80:
			return R.drawable.face_80;
		case 81:
			return R.drawable.face_81;
		case 82:
			return R.drawable.face_82;
		case 83:
			return R.drawable.face_83;
		case 84:
			return R.drawable.face_84;
		case 85:
			return R.drawable.face_85;
		case 86:
			return R.drawable.face_86;
		case 87:
			return R.drawable.face_87;
		case 88:
			return R.drawable.face_88;
		case 89:
			return R.drawable.face_89;
		case 90:
			return R.drawable.face_90;
		case 91:
			return R.drawable.face_91;
		case 92:
			return R.drawable.face_92;
		case 93:
			return R.drawable.face_93;
		case 94:
			return R.drawable.face_94;
		case 95:
			return R.drawable.face_95;
		case 96:
			return R.drawable.face_96;
		case 97:
			return R.drawable.face_97;
		case 98:
			return R.drawable.face_98;
		case 99:
			return R.drawable.face_99;
		case 100:
			return R.drawable.face_100;
		case 101:
			return R.drawable.face_101;
		case 102:
			return R.drawable.face_102;
		case 103:
			return R.drawable.face_103;
		case 104:
			return R.drawable.face_104;
		case 105:
			return R.drawable.face_105;
		case 106:
			return R.drawable.face_106;
		case 107:
			return R.drawable.face_107;
		case 108:
			return R.drawable.face_108;
		case 109:
			return R.drawable.face_109;
		case 110:
			return R.drawable.face_110;
		case 111:
			return R.drawable.face_111;
		case 112:
			return R.drawable.face_112;
		case 113:
			return R.drawable.face_113;
		case 114:
			return R.drawable.face_114;
		case 115:
			return R.drawable.face_115;

		default:
			return 0;
		}
	}

	public static int getUserFace(int faceId) {
		switch (faceId) {
		case 0:
			return R.drawable.userface_1;
		case 1:
			return R.drawable.userface_2;
		case 2:
			return R.drawable.userface_3;
		case 3:
			return R.drawable.userface_4;
		case 4:
			return R.drawable.userface_5;
		case 5:
			return R.drawable.userface_6;
		case 6:
			return R.drawable.userface_7;
		case 7:
			return R.drawable.userface_8;
		case 8:
			return R.drawable.userface_9;
		case 9:
			return R.drawable.userface_10;
		case 10:
			return R.drawable.userface_11;
		case 11:
			return R.drawable.userface_12;
		case 12:
			return R.drawable.userface_13;
		case 13:
			return R.drawable.userface_14;
		case 14:
			return R.drawable.userface_15;
		case 15:
			return R.drawable.userface_16;
		case 16:
			return R.drawable.userface_17;
		case 17:
			return R.drawable.userface_18;
		case 18:
			return R.drawable.userface_19;
		case 19:
			return R.drawable.userface_20;
		case 20:
			return R.drawable.userface_21;
		case 21:
			return R.drawable.userface_22;
		case 22:
			return R.drawable.userface_23;
		case 23:
			return R.drawable.userface_24;
		case 24:
			return R.drawable.userface_25;
		case 25:
			return R.drawable.userface_26;
		case 26:
			return R.drawable.userface_27;
		case 27:
			return R.drawable.userface_28;
		case 28:
			return R.drawable.userface_29;
		case 29:
			return R.drawable.userface_30;
		case 30:
			return R.drawable.userface_31;
		case 31:
			return R.drawable.userface_32;
		case 32:
			return R.drawable.userface_33;
		case 33:
			return R.drawable.userface_34;
		case 34:
			return R.drawable.userface_35;
		case 35:
			return R.drawable.userface_36;
		case 36:
			return R.drawable.userface_37;
		case 37:
			return R.drawable.userface_38;
		case 38:
			return R.drawable.userface_39;
		case 39:
			return R.drawable.userface_40;
		case 40:
			return R.drawable.userface_41;
		case 41:
			return R.drawable.userface_42;
		case 42:
			return R.drawable.userface_43;
		case 43:
			return R.drawable.userface_44;
		case 44:
			return R.drawable.userface_45;
		case 45:
			return R.drawable.userface_46;
		case 46:
			return R.drawable.userface_47;
		case 47:
			return R.drawable.userface_48;
		case 48:
			return R.drawable.userface_49;
		case 49:
			return R.drawable.userface_50;
		case 50:
			return R.drawable.userface_51;
		case 51:
			return R.drawable.userface_52;
		case 52:
			return R.drawable.userface_53;
		case 53:
			return R.drawable.userface_54;
		case 54:
			return R.drawable.userface_55;
		case 55:
			return R.drawable.userface_56;
		case 56:
			return R.drawable.userface_57;
		case 57:
			return R.drawable.userface_58;
		case 58:
			return R.drawable.userface_59;
		case 59:
			return R.drawable.userface_60;
		case 60:
			return R.drawable.userface_61;
		case 61:
			return R.drawable.userface_62;
		case 62:
			return R.drawable.userface_63;
		case 63:
			return R.drawable.userface_64;
		case 64:
			return R.drawable.userface_65;
		case 65:
			return R.drawable.userface_66;
		case 66:
			return R.drawable.userface_67;
		case 67:
			return R.drawable.userface_68;
		case 68:
			return R.drawable.userface_69;
		case 69:
			return R.drawable.userface_70;
		case 70:
			return R.drawable.userface_71;
		case 71:
			return R.drawable.userface_72;
		case 72:
			return R.drawable.userface_73;
		case 73:
			return R.drawable.userface_74;
		case 74:
			return R.drawable.userface_75;
		case 75:
			return R.drawable.userface_76;
		case 76:
			return R.drawable.userface_77;
		case 77:
			return R.drawable.userface_78;
		case 78:
			return R.drawable.userface_79;
		case 79:
			return R.drawable.userface_80;
		case 80:
			return R.drawable.userface_81;
		case 81:
			return R.drawable.userface_82;
		case 82:
			return R.drawable.userface_83;
		case 83:
			return R.drawable.userface_84;
		case 84:
			return R.drawable.userface_85;
		case 85:
			return R.drawable.userface_86;
		case 86:
			return R.drawable.userface_87;
		case 87:
			return R.drawable.userface_88;
		case 88:
			return R.drawable.userface_89;
		case 89:
			return R.drawable.userface_90;
		case 90:
			return R.drawable.userface_91;
		case 91:
			return R.drawable.userface_92;
		case 92:
			return R.drawable.userface_93;
		case 93:
			return R.drawable.userface_94;
		case 94:
			return R.drawable.userface_95;
		case 95:
			return R.drawable.userface_96;
		case 96:
			return R.drawable.userface_97;
		case 97:
			return R.drawable.userface_98;

		default:
			return R.drawable.userface_1;
		}
	}
	
	public static int getUserFaceGray(int faceId) {
		switch (faceId) {
		case 0:
			return R.drawable.userface_1_gray;
		case 1:
			return R.drawable.userface_2_gray;
		case 2:
			return R.drawable.userface_3_gray;
		case 3:
			return R.drawable.userface_4_gray;
		case 4:
			return R.drawable.userface_5_gray;
		case 5:
			return R.drawable.userface_6_gray;
		case 6:
			return R.drawable.userface_7_gray;
		case 7:
			return R.drawable.userface_8_gray;
		case 8:
			return R.drawable.userface_9_gray;
		case 9:
			return R.drawable.userface_10_gray;
		case 10:
			return R.drawable.userface_11_gray;
		case 11:
			return R.drawable.userface_12_gray;
		case 12:
			return R.drawable.userface_13_gray;
		case 13:
			return R.drawable.userface_14_gray;
		case 14:
			return R.drawable.userface_15_gray;
		case 15:
			return R.drawable.userface_16_gray;
		case 16:
			return R.drawable.userface_17_gray;
		case 17:
			return R.drawable.userface_18_gray;
		case 18:
			return R.drawable.userface_19_gray;
		case 19:
			return R.drawable.userface_20_gray;
		case 20:
			return R.drawable.userface_21_gray;
		case 21:
			return R.drawable.userface_22_gray;
		case 22:
			return R.drawable.userface_23_gray;
		case 23:
			return R.drawable.userface_24_gray;
		case 24:
			return R.drawable.userface_25_gray;
		case 25:
			return R.drawable.userface_26_gray;
		case 26:
			return R.drawable.userface_27_gray;
		case 27:
			return R.drawable.userface_28_gray;
		case 28:
			return R.drawable.userface_29_gray;
		case 29:
			return R.drawable.userface_30_gray;
		case 30:
			return R.drawable.userface_31_gray;
		case 31:
			return R.drawable.userface_32_gray;
		case 32:
			return R.drawable.userface_33_gray;
		case 33:
			return R.drawable.userface_34_gray;
		case 34:
			return R.drawable.userface_35_gray;
		case 35:
			return R.drawable.userface_36_gray;
		case 36:
			return R.drawable.userface_37_gray;
		case 37:
			return R.drawable.userface_38_gray;
		case 38:
			return R.drawable.userface_39_gray;
		case 39:
			return R.drawable.userface_40_gray;
		case 40:
			return R.drawable.userface_41_gray;
		case 41:
			return R.drawable.userface_42_gray;
		case 42:
			return R.drawable.userface_43_gray;
		case 43:
			return R.drawable.userface_44_gray;
		case 44:
			return R.drawable.userface_45_gray;
		case 45:
			return R.drawable.userface_46_gray;
		case 46:
			return R.drawable.userface_47_gray;
		case 47:
			return R.drawable.userface_48_gray;
		case 48:
			return R.drawable.userface_49_gray;
		case 49:
			return R.drawable.userface_50_gray;
		case 50:
			return R.drawable.userface_51_gray;
		case 51:
			return R.drawable.userface_52_gray;
		case 52:
			return R.drawable.userface_53_gray;
		case 53:
			return R.drawable.userface_54_gray;
		case 54:
			return R.drawable.userface_55_gray;
		case 55:
			return R.drawable.userface_56_gray;
		case 56:
			return R.drawable.userface_57_gray;
		case 57:
			return R.drawable.userface_58_gray;
		case 58:
			return R.drawable.userface_59_gray;
		case 59:
			return R.drawable.userface_60_gray;
		case 60:
			return R.drawable.userface_61_gray;
		case 61:
			return R.drawable.userface_62_gray;
		case 62:
			return R.drawable.userface_63_gray;
		case 63:
			return R.drawable.userface_64_gray;
		case 64:
			return R.drawable.userface_65_gray;
		case 65:
			return R.drawable.userface_66_gray;
		case 66:
			return R.drawable.userface_67_gray;
		case 67:
			return R.drawable.userface_68_gray;
		case 68:
			return R.drawable.userface_69_gray;
		case 69:
			return R.drawable.userface_70_gray;
		case 70:
			return R.drawable.userface_71_gray;
		case 71:
			return R.drawable.userface_72_gray;
		case 72:
			return R.drawable.userface_73_gray;
		case 73:
			return R.drawable.userface_74_gray;
		case 74:
			return R.drawable.userface_75_gray;
		case 75:
			return R.drawable.userface_76_gray;
		case 76:
			return R.drawable.userface_77_gray;
		case 77:
			return R.drawable.userface_78_gray;
		case 78:
			return R.drawable.userface_79_gray;
		case 79:
			return R.drawable.userface_80_gray;
		case 80:
			return R.drawable.userface_81_gray;
		case 81:
			return R.drawable.userface_82_gray;
		case 82:
			return R.drawable.userface_83_gray;
		case 83:
			return R.drawable.userface_84_gray;
		case 84:
			return R.drawable.userface_85_gray;
		case 85:
			return R.drawable.userface_86_gray;
		case 86:
			return R.drawable.userface_87_gray;
		case 87:
			return R.drawable.userface_88_gray;
		case 88:
			return R.drawable.userface_89_gray;
		case 89:
			return R.drawable.userface_90_gray;
		case 90:
			return R.drawable.userface_91_gray;
		case 91:
			return R.drawable.userface_92_gray;
		case 92:
			return R.drawable.userface_93_gray;
		case 93:
			return R.drawable.userface_94_gray;
		case 94:
			return R.drawable.userface_95_gray;
		case 95:
			return R.drawable.userface_96_gray;
		case 96:
			return R.drawable.userface_97_gray;
		case 97:
			return R.drawable.userface_98_gray;

		default:
			return R.drawable.userface_1_gray;
		}
	}

}
